INSERT INTO okresy (nazov, kraj_id)
VALUES ('Banská Bystrica', 1),
       ('Banská Štiavnica', 1),
       ('Brezno', 1),
       ('Detva', 1),
       ('Krupina', 1),
       ('Lučenec', 1),
       ('Poltár', 1),
       ('Revúca', 1),
       ('Rimavská Sobota', 1),
       ('Veľký Krtíš', 1),
       ('Zvolen', 1),
       ('Žarnovica', 1),
       ('Žiar nad Hronom', 1),
       ('Bratislava 1', 2),
       ('Bratislava 2', 2),
       ('Bratislava 3', 2),
       ('Bratislava 4', 2),
       ('Bratislava 5', 2),
       ('Malacky', 2),
       ('Pezinok', 2),
       ('Senec', 2),
       ('Gelnica', 3),
       ('Košice 1', 3),
       ('Košice 2', 3),
       ('Košice 3', 3),
       ('Košice 4', 3),
       ('Košice-okolie', 3),
       ('Michalovce', 3),
       ('Rožňava', 3),
       ('Sobrance', 3),
       ('Spišská Nová Ves', 3),
       ('Trebišov', 3),
       ('Komárno', 4),
       ('Levice', 4),
       ('Nitra', 4),
       ('Nové Zámky', 4),
       ('Šaľa', 4),
       ('Topoľčany', 4),
       ('Zlaté Moravce', 4),
       ('Bardejov', 5),
       ('Humenné', 5),
       ('Kežmarok', 5),
       ('Levoča', 5),
       ('Medzilaborce', 5),
       ('Poprad', 5),
       ('Prešov', 5),
       ('Sabinov', 5),
       ('Snina', 5),
       ('Stará Ľubovňa', 5),
       ('Stropkov', 5),
       ('Svidník', 5),
       ('Vranov nad Topľou', 5),
       ('Bánovce nad Bebravou', 6),
       ('Ilava', 6),
       ('Myjava', 6),
       ('Nové Mesto nad Váhom', 6),
       ('Partizánske', 6),
       ('Považská Bystrica', 6),
       ('Prievidza', 6),
       ('Púchov', 6),
       ('Trenčín', 6),
       ('Dunajská Streda', 7),
       ('Galanta', 7),
       ('Hlohovec', 7),
       ('Piešťany', 7),
       ('Senica', 7),
       ('Skalica', 7),
       ('Trnava', 7),
       ('Bytča', 8),
       ('Čadca', 8),
       ('Dolný Kubín', 8),
       ('Kysucké Nové Mesto', 8),
       ('Liptovský Mikuláš', 8),
       ('Martin', 8),
       ('Námestovo', 8),
       ('Ružomberok', 8),
       ('Turčianske Teplice', 8),
       ('Tvrdošín', 8),
       ('Žilina', 8)
